- hosts: localhost
  sudo: yes
  remote_user: vagrant
  vars:
    mysql_root_password: 
  tasks:
  - name: Actualizar sistema 
    apt: update_cache=yes upgrade=dist 
  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    sudo: yes
    with_items:
    - python-mysqldb
    - mysql-server
  - name: Arrancar servicio MySQL 
    sudo: yes
    service: 
      name: mysql 
      state: started
      enabled: true
  - name: actualizacion password root mysql
    sudo: yes
    mysql_user: 
      name: root 
      host: "{{ item }}" 
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost 
  - name: Instalar paquetes
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    sudo: yes
    with_items:
    - python-setuptools
    - build-essential 
    - python-pip
    - git 
  - name: Instalar servidor Gunicorn
    command: sudo pip install gunicorn
  - name: Instalar servidor Nginx y supervisor
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    sudo: yes
    with_items:
    - nginx
    - supervisor  
  - name: Conector Postgre Heroku
    command: sudo easy_install pip
    command: sudo pip install --upgrade pip
    command: sudo apt-get install -y python-dev libpq-dev python-psycopg2
  - name: Obtener aplicacion git
    git: repo=https://github.com/javiergarridomellado/DAI.git  dest=DAI clone=yes force=yes
  - name: Permisos de ejecucion
    command: chmod -R +x DAI
  - name: Instalar requisitos
    command: sudo pip install -r DAI/requirements.txt
  - name: Crear www 
    command: sudo mkdir -p /var/www
  - name: Copiar static
    command: sudo cp -r DAI/static/ /var/www/
  - name: Copiar media
    command: sudo cp -r DAI/media/ /var/www/
  - name: Conf supervisor
    command: sudo mv DAI/scripts/webconfiguration/supervisor.conf /etc/supervisor/conf.d/
  - name: Conf nginx
    command: sudo mv DAI/scripts/webconfiguration/default /etc/nginx/sites-available/
  - name: crear bd
    command: mysqladmin  -h localhost -u root  create vagrant
  #- name: app configuracion modo produccion 
    #command: sudo mv DAI/ProyectoDAI/settings.py DAI/ProyectoDAI/bak_settings.py
    #command: sudo mv DAI/ProyectoDAI/bak2_settings.py DAI/ProyectoDAI/settings.py
  - name: sincro bd
    command: sudo python DAI/manage.py syncdb --noinput
  - name: update bd
    command: sudo python DAI/populate_restaurante.py
  - name: Reiniciar Supervisor 
    sudo: yes
    service: 
      name: supervisor 
      state: restarted
      enabled: true
  - name: Reiniciar Nginx 
    sudo: yes
    service: 
      name: nginx 
      state: restarted
      enabled: true
    #command: sudo service nginx restart
    #command: sudo service supervisor restart
  #- name: ejecutar
    #command: nohup sudo python DAI/manage.py runserver 0.0.0.0:80

